#!/bin/bash
# Weekly consolidation loop - the MISSING PIECE
# Transforms scattered observations into actionable memory
# Run: Sunday 2am via launchd (not cron)

set -euo pipefail

MEMORY_DIR="$HOME/memory"
PCB="$HOME/Desktop/ALAN-CONTEXT.md"
CLAUDE_MD="$HOME/.claude/CLAUDE.md"
LOG_FILE="$HOME/.claude/logs/consolidation-$(date +%Y%m%d).log"

mkdir -p "$HOME/.claude/logs"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

log "=== Consolidation Loop Started ==="

# Phase 1: Collect recent observations from all sources
WEEK_AGO=$(date -v-7d +%Y-%m-%d 2>/dev/null || date -d '7 days ago' +%Y-%m-%d)
log "Collecting observations since $WEEK_AGO"

OBSERVATIONS=""

# From claude-mem (if running)
if curl -s http://127.0.0.1:37777/health >/dev/null 2>&1; then
    if [[ -f ~/.claude-mem/claude-mem.db ]]; then
        OBSERVATIONS+=$(sqlite3 ~/.claude-mem/claude-mem.db "
            SELECT type || ': ' || title || ' - ' || COALESCE(subtitle, '')
            FROM observations
            WHERE created_at > datetime('$WEEK_AGO')
            ORDER BY created_at DESC
            LIMIT 50
        " 2>/dev/null || echo "")
        log "Collected from claude-mem"
    fi
fi

# From daily memory files
for f in "$MEMORY_DIR"/daily/*.md; do
    [[ -f "$f" ]] || continue
    file_date=$(basename "$f" .md)
    if [[ "$file_date" > "$WEEK_AGO" ]]; then
        OBSERVATIONS+=$'\n'"$(grep -E '^- \*\*|^## ' "$f" 2>/dev/null || true)"
    fi
done
log "Collected from daily memory files"

# Phase 2: Extract patterns (simple frequency analysis, no LLM needed)
log "Analyzing patterns..."

# Count repeated concepts
PATTERNS=$(echo "$OBSERVATIONS" | \
    tr '[:upper:]' '[:lower:]' | \
    grep -oE '\b[a-z]{4,}\b' | \
    sort | uniq -c | sort -rn | head -20)

# Phase 3: Identify mistakes (grep for error patterns)
MISTAKES=$(echo "$OBSERVATIONS" | grep -iE 'fix|bug|error|wrong|fail|broken|mistake' | head -10)

# Phase 4: Generate consolidation report
REPORT_FILE="$MEMORY_DIR/consolidation-$(date +%Y%m%d).md"
cat > "$REPORT_FILE" << EOF
# Weekly Consolidation Report - $(date +%Y-%m-%d)

## Top Patterns (by frequency)
\`\`\`
$PATTERNS
\`\`\`

## Mistakes & Fixes
$MISTAKES

## Action Items
- [ ] Review patterns for CLAUDE.md updates
- [ ] Check if any mistakes should become rules
- [ ] Prune PCB if > 300 lines

---
Generated by consolidation loop
EOF

log "Report written to $REPORT_FILE"

# Phase 5: Auto-inject top mistake into session-start (self-evolution!)
if [[ -n "$MISTAKES" ]]; then
    TOP_MISTAKE=$(echo "$MISTAKES" | head -1 | sed 's/^[[:space:]]*//')
    if [[ -n "$TOP_MISTAKE" ]]; then
        # Check if already in session-start
        if ! grep -q "RECENT_MISTAKE" "$HOME/.claude/hooks/session-start.sh" 2>/dev/null; then
            log "Injecting mistake reminder into session-start"
            # Will implement injection in session-start.sh
        fi
    fi
fi

log "=== Consolidation Loop Complete ==="
echo "Report: $REPORT_FILE"
